name: wtv
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_ui_auth: ^1.16.0
  flutter_localizations:
    sdk: flutter
  firebase_ui_localizations: ^1.13.0
  cloud_firestore: ^5.4.4
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


